\W
USE codeup_test_db;
CREATE TABLE IF NOT EXISTS albums(
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
 artist VARCHAR(60) NOT NULL,
 record_name VARCHAR(30) NOT NULL,
 release_date INT(4) UNSIGNED NOT NULL,
 sales DECIMAL(11,2) UNSIGNED NOT NULL,
 genre VARCHAR(30) NOT NULL,
 PRIMARY KEY (id)
);
